# Generated by Django 2.2.12 on 2021-11-14 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('commit_id', models.CharField(blank=True, max_length=1000)),
                ('project_name', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
